"""add total_price to sales

Revision ID: 1c23ce79128e
Revises: 1a9c419e03f4
Create Date: 2025-04-10 12:41:18.177559

"""
from typing import Sequence, Union
from sqlalchemy.orm import Session
from alembic import op
import sqlalchemy as sa

from app.models import Product, Sale


# revision identifiers, used by Alembic.
revision: str = '1c23ce79128e'
down_revision: Union[str, None] = '1a9c419e03f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('total_price', sa.Float(), nullable=True))

    bind = op.get_bind()
    session = Session(bind=bind)

    sales = session.query(Sale).all()
    for sale in sales:
        product = session.query(Product).get(sale.product_id)
        if product:
            discount_amount = (sale.discount or 0) * product.price * sale.quantity
            sale.total_price = round((product.price * sale.quantity) - discount_amount, 2)

    session.commit()

    op.alter_column('sales', 'total_price', existing_type=sa.Float(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'total_price')
    # ### end Alembic commands ###
